Story/gh50 search matching
Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface pull request #216
Opened 2021-01-07 15:41 UTC by bakerac4

2021-01-07 16:00 UTC, bakerac4 commented
Fixes #50

2021-01-07 16:38 UTC, billdami requested changes

2021-01-07 16:38 UTC, billdami commented on pep/app/pods/read/document/template.hbs
> +                        {{this.q}}
do search hits only come from "smart search"-based queries (which is what `q` holds), or can hits also occur from fulltext search term-based hits? If its the latter, i think you'd need a bit more logic here to build this displayed text value

2021-01-08 18:50 UTC, billdami approved these changes

2021-01-08 18:51 UTC, merged